// Auto-generated by scripts/generate-photo-manifest.mjs — do not edit by hand
export const PHOTOS = [
  {
    "file": "IMG_0113.jpg",
    "taken": "2026-03-15T17:49:33"
  },
  {
    "file": "IMG_0114.jpg",
    "taken": "2026-03-15T17:49:35"
  },
  {
    "file": "IMG_0115.jpg",
    "taken": "2026-03-15T17:49:36"
  },
  {
    "file": "IMG_0116.jpg",
    "taken": "2026-03-15T17:49:37"
  },
  {
    "file": "IMG_0117.jpg",
    "taken": "2026-03-15T17:49:40"
  },
  {
    "file": "IMG_0403.jpg",
    "taken": "2026-03-26T12:01:56"
  },
  {
    "file": "IMG_0437.jpg",
    "taken": "2026-03-29T13:58:19"
  },
  {
    "file": "IMG_0591.jpg",
    "taken": "2026-04-09T13:57:58"
  },
  {
    "file": "IMG_0656.jpg",
    "taken": "2026-04-11T19:34:26"
  },
  {
    "file": "IMG_0737.jpg",
    "taken": "2026-06-24T13:33:21"
  },
  {
    "file": "IMG_1784.jpg",
    "taken": "2026-04-30T15:52:13"
  },
  {
    "file": "IMG_1801.jpg",
    "taken": "2026-05-01T14:04:32"
  },
  {
    "file": "IMG_2084.jpg",
    "taken": "2026-02-23T16:58:47"
  },
  {
    "file": "IMG_2093.jpg",
    "taken": "2026-05-08T18:44:41"
  },
  {
    "file": "IMG_2302.jpg",
    "taken": "2026-05-17T12:05:21"
  },
  {
    "file": "IMG_2303.jpg",
    "taken": "2026-05-17T12:05:23"
  },
  {
    "file": "IMG_2328.jpg",
    "taken": "2026-05-17T15:37:18"
  },
  {
    "file": "IMG_2426.jpg",
    "taken": "2026-05-21T15:37:26"
  },
  {
    "file": "IMG_2998.jpg",
    "taken": "2026-05-31T13:41:57"
  },
  {
    "file": "IMG_3026.jpg",
    "taken": "2026-05-31T17:22:14"
  },
  {
    "file": "IMG_3108.jpg",
    "taken": "2026-06-04T17:30:27"
  },
  {
    "file": "IMG_3283.jpg",
    "taken": "2026-06-13T13:57:52"
  },
  {
    "file": "IMG_3332.jpg",
    "taken": "2026-06-15T12:23:44"
  },
  {
    "file": "IMG_3333.jpg",
    "taken": "2026-06-15T12:23:45"
  },
  {
    "file": "IMG_3351.jpg",
    "taken": "2026-06-15T12:42:41"
  },
  {
    "file": "IMG_3359.jpg",
    "taken": "2026-06-15T12:42:53"
  },
  {
    "file": "IMG_3362.jpg",
    "taken": "2026-06-15T12:42:54"
  },
  {
    "file": "IMG_3452.jpg",
    "taken": "2026-06-18T13:16:36"
  },
  {
    "file": "IMG_3457.jpg",
    "taken": "2026-06-18T13:19:38"
  },
  {
    "file": "IMG_3458.jpg",
    "taken": "2026-06-18T13:19:39"
  },
  {
    "file": "IMG_8888.jpg",
    "taken": "2026-02-11T13:07:03"
  },
  {
    "file": "IMG_9048.jpg",
    "taken": "2026-02-18T11:17:03"
  },
  {
    "file": "IMG_9252.jpg",
    "taken": "2026-02-23T08:38:42"
  },
  {
    "file": "IMG_9272.jpg",
    "taken": "2026-02-23T16:46:37"
  },
  {
    "file": "IMG_9325.jpg",
    "taken": "2026-02-25T10:38:59"
  },
  {
    "file": "IMG_9330.jpg",
    "taken": "2026-02-25T10:40:16"
  },
  {
    "file": "IMG_9340.jpg",
    "taken": "2026-02-25T16:18:32"
  },
  {
    "file": "IMG_9802.jpg",
    "taken": "2026-03-20T18:44:26"
  },
  {
    "file": "IMG_9808.jpg",
    "taken": "2026-03-20T20:06:58"
  }
];
