// Auto-generated by scripts/generate-photo-manifest.mjs — do not edit by hand
export const PHOTOS = [
  "IMG_0117.jpg",
  "IMG_0403.jpg",
  "IMG_0591.jpg",
  "IMG_0656.jpg",
  "IMG_2084.jpg",
  "IMG_2093.jpg",
  "IMG_2302.jpg",
  "IMG_3026.jpg",
  "IMG_3333.jpg",
  "IMG_3351.jpg",
  "IMG_3458.jpg",
  "IMG_9252.jpg",
  "IMG_9325.jpg",
  "IMG_9340.jpg",
  "IMG_9802.jpg",
  "IMG_9808.jpg"
];
